config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :properties, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  validates :title, :property_location, :property_type, :rooms,
            :daily_rate, :photo, :area, :description,
            :minimum_rent_days, :maximum_rent_days,
            :maximum_occupancy, :usage_rules, presence: true

  has_attached_file :photo
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def extract_locale_from_subdomain
    parsed_locale = request.subdomains.first
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @properties = Property.all
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def new
    @property = Property.new
  end
  def create
    @property = Property.new(property_params)
    if @property.save
      flash[:notice] = 'Imóvel cadastrado com sucesso!'
      redirect_to @property
    else
      render :new
    end
  end
  def show
    @property = Property.find(params[:id])
  end
  private
  def property_params
    params.require(:property).permit(:property_location, :area, :title,
                                  :description, :daily_rate, :rooms,
                                  :minimum_rent_days,
                                   :maximum_rent_days, :photo,
                                   :maximum_occupancy, :usage_rules,
                                   :property_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1><%=t :site_name %></h1>
<%= link_to 'Anunciar um imóvel', new_property_path %>
<% if @properties.any? %>
  <% @properties.each do |property| %>
    <div><%= image_tag property.photo %></div>
    <h2><%= property.title %></h2>
    <dl>
      <dt><%= t('location_label') %>:</dt> <dd><%= property.property_location %></dd>
      <dt>Tipo:</dt> <dd><%= property.property_type %></dd>
      <dt>Quartos:</dt> <dd><%= property.rooms %></dd>
      <dt>Diária:</dt> <dd><%= number_to_currency(property.daily_rate) %></dd>
    </dl>
  <% end %>
<% else %>
  <div class="error">Ainda não existem imóveis para serem exibidos</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AluguelTemporada</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/new.html.erb
<% if @property.errors.any? %>
  <ul>
    <% @property.errors.full_messages.each do |error| %>
      <li class="error"><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @property, html: { multipart: true } do |f| %>
  <fieldset>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
  <br>
    <%= f.label :property_location, 'Localização' %>
    <%= f.text_field :property_location %>
  <br>
    <%= f.label :area, 'Tamanho (m²)' %>
    <%= f.text_field :area %>
  <br>
    <%= f.label :property_type, 'Tipo do Imóvel' %>
    <%= f.text_field :property_type %>
  <br>
    <%= f.label :rooms, 'Quantidade de quartos' %>
    <%= f.text_field :rooms %>
  <br>
    <%= f.label :maximum_occupancy, 'Máximo de pessoas' %>
    <%= f.text_field :maximum_occupancy %>
  <br>
    <%= f.label :minimum_rent_days, 'Mínimo de dias para locação' %>
    <%= f.text_field :minimum_rent_days %>
  <br>
    <%= f.label :maximum_rent_days, 'Máximo de dias para locação' %>
    <%= f.text_field :maximum_rent_days %>
  <br>
    <%= f.label :daily_rate, 'Valor padrão da diária' %>
    <%= f.text_field :daily_rate %>
  <br>
    <%= f.label :photo, 'Foto' %>
    <%= f.file_field :photo %>
  <br>
    <%= f.label :description, 'Descrição' %>
    <%= f.text_area :description %>
  <br>
    <%= f.label :usage_rules, 'Regras de uso' %>
    <%= f.text_field :usage_rules %>
  <br>
    <%= f.submit 'Cadastrar' %>
  </fieldset>
<% end %>

app/views/properties/show.html.erb
<% if flash['notice'] %>
  <div class="success"><%= flash['notice'] %></div>
<% end %>

<%= link_to 'Voltar', root_path %>

<div>
    <h1 class="mt-5 text-success"><%= @property.title %></h1>
    <%= image_tag @property.photo %>
    <h2>Detalhes</h2>
    <dl>
      <dt>Descrição:</dt>
      <dd><%= @property.description %></dd>
      <dt>Localização:</dt>
      <dd><%= @property.property_location %></dd>
      <dt>Tamanho (m²):</dt>
      <dd><%= @property.area %> m²</dd>
      <dt>Tipo do Imóvel</dt>
      <dd><%= @property.property_type %></dd>
      <dt>Quantidade de quartos</dt>
      <dd><%= @property.rooms %></dd>
      <dt>Máximo de pessoas</dt>
      <dd><%= @property.maximum_occupancy %></dd>
      <dt>Mínimo de dias para locação</dt>
      <dd><%= @property.minimum_rent_days %></dd>
      <dt>Máximo de dias para locação</dt>
      <dd><%= @property.maximum_rent_days %></dd>

      <dt>Valor padrão da diária</dt>
      <dd><%= number_to_currency(@property.daily_rate) %></dd>
      <dt>Regras de uso:</dt>
      <dd><%= @property.usage_rules %></dd>
    </dl>
  </div>